= Couchbase Swagger Project

This project uses the https://github.com/Swagger2Markup/swagger2markup-gradle-plugin[swagger2markup-gradle-plugin] to convert the Swagger specifications for Couchbase REST APIs into AsciiDoctor documentation.

== Usage guide

This repository handles several Swagger subprojects.
Each subproject is stored in its own subfolder within the `src` folder.

=== Build Script

In the project root folder there is a gradle build script with a `.gradle` extension.
The gradle build script specifies the locations of the Swagger source file, any additional AsciiDoc content, and the output AsciiDoc files.

Some subprojects are not currently designed to be built.
These do not have a gradle build script.

=== Swagger Specification

Within each subproject, the Swagger Specification (JSON or YAML) is stored in a folder called `swagger`.
(For some subprojects, the Swagger specification file may be stored remotely, i.e. alongside the development source files.)

=== AsciiDoc Content

For each subproject, additional AsciiDoc content may be stored in the folder `asciidoc/extensions` and its subfolders.

=== Convert all projects

[subs="normal"]
----
./gradlew --rerun-tasks
----

== Acknowledgements

This project is based on the https://github.com/Swagger2Markup/swagger2markup-gradle-project-template[Swagger2Markup Gradle template project].